


select * from marketing_campaigns

select * from sustainable_clothing

select * from transactions


--1. How many transactions were completed during each marketing campaign?

Select mc.campaign_id, mc.campaign_name, COUNT(t.transaction_id) as transaction_count
From marketing_campaigns mc
LEFT JOIN transactions t 
    ON mc.product_id = t.product_id
    AND t.purchase_date BETWEEN mc.start_date AND mc.end_date
Group by mc.campaign_id, mc.campaign_name;

-- 2. Which product had the highest sales quantity?

Select sc.product_id, sc.product_name, SUM(t.quantity) as total_quantity_sold
From sustainable_clothing sc
JOIN transactions t ON sc.product_id = t.product_id
Group by sc.product_id, sc.product_name
Order by total_quantity_sold desc

-- 3. What is the total revenue generated from each marketing campaign?

Select mc.campaign_id, mc.campaign_name, SUM(t.quantity * sc.price) AS total_revenue
From marketing_campaigns mc
JOIN transactions t 
    ON mc.product_id = t.product_id
    AND t.purchase_date BETWEEN mc.start_date AND mc.end_date
JOIN sustainable_clothing sc 
    ON mc.product_id = sc.product_id
Group by mc.campaign_id, mc.campaign_name
Order by total_revenue desc;

-- 4. What is the top-selling product category based on the total revenue generated?

Select sc.category, SUM(t.quantity * sc.price) AS total_revenue
From sustainable_clothing sc
JOIN transactions t ON sc.product_id = t.product_id
Group by sc.category
Order by total_revenue desc

-- 5. Which products had a higher quantity sold compared to the average quantity sold?

WITH avg_quantity AS (
    SELECT AVG(quantity) AS avg_qty
    FROM transactions
)
SELECT sc.product_id, sc.product_name, SUM(t.quantity) AS total_quantity_sold
FROM sustainable_clothing sc
JOIN transactions t ON sc.product_id = t.product_id
GROUP BY sc.product_id, sc.product_name
HAVING SUM(t.quantity) > (SELECT avg_qty FROM avg_quantity)
ORDER BY total_quantity_sold DESC;


-- 6. What is the average revenue generated per day during the marketing campaigns?
WITH campaign_revenue AS (
    SELECT mc.campaign_id, mc.campaign_name, 
           SUM(t.quantity * sc.price) AS total_revenue,
           DATEDIFF(day, mc.start_date, mc.end_date) + 1 AS campaign_duration
    FROM marketing_campaigns mc
    JOIN transactions t 
        ON mc.product_id = t.product_id
        AND t.purchase_date BETWEEN mc.start_date AND mc.end_date
    JOIN sustainable_clothing sc 
        ON mc.product_id = sc.product_id
    GROUP BY mc.campaign_id, mc.campaign_name, mc.start_date, mc.end_date
)
SELECT campaign_id, campaign_name, 
       total_revenue / campaign_duration AS avg_revenue_per_day
FROM campaign_revenue
ORDER BY avg_revenue_per_day DESC;


-- 7. What is the percentage contribution of each product to the total revenue?

WITH product_revenue AS (
    SELECT sc.product_id, sc.product_name, SUM(t.quantity * sc.price) AS total_revenue
    FROM sustainable_clothing sc
    JOIN transactions t ON sc.product_id = t.product_id
    GROUP BY sc.product_id, sc.product_name
),
total_revenue AS (
    SELECT SUM(total_revenue) AS grand_total FROM product_revenue
)
SELECT pr.product_id, pr.product_name, pr.total_revenue, 
       (pr.total_revenue / tr.grand_total) * 100 AS revenue_percentage
FROM product_revenue pr
CROSS JOIN total_revenue tr
ORDER BY revenue_percentage DESC;

-- 8. Compare the average quantity sold during marketing campaigns to outside the marketing campaigns

SELECT 
    CASE 
        WHEN mc.campaign_id IS NOT NULL THEN 'During Campaign' 
        ELSE 'Outside Campaign' 
    END AS sales_period,
    AVG(t.quantity) AS avg_quantity_sold
FROM transactions t
LEFT JOIN marketing_campaigns mc 
    ON t.product_id = mc.product_id 
    AND t.purchase_date BETWEEN mc.start_date AND mc.end_date
GROUP BY 
    CASE 
        WHEN mc.campaign_id IS NOT NULL THEN 'During Campaign' 
        ELSE 'Outside Campaign' 
    END;


	-- 9. Compare the revenue generated by products inside the marketing campaigns to outside the campaigns

SELECT 
    CASE 
        WHEN mc.campaign_id IS NOT NULL THEN 'During Campaign' 
        ELSE 'Outside Campaign' 
    END AS sales_period,
    SUM(t.quantity * sc.price) AS total_revenue
FROM transactions t
JOIN sustainable_clothing sc ON t.product_id = sc.product_id
LEFT JOIN marketing_campaigns mc 
    ON t.product_id = mc.product_id 
    AND t.purchase_date BETWEEN mc.start_date AND mc.end_date
GROUP BY 
    CASE 
        WHEN mc.campaign_id IS NOT NULL THEN 'During Campaign' 
        ELSE 'Outside Campaign' 
    END;

-- 10. Rank the products by their average daily quantity sold	
WITH daily_sales AS (
    SELECT 
        t.product_id, 
        sc.product_name,
        COUNT(DISTINCT t.purchase_date) AS active_days,
        SUM(t.quantity) AS total_quantity
    FROM transactions t
    JOIN sustainable_clothing sc ON t.product_id = sc.product_id
    GROUP BY t.product_id, sc.product_name
)
SELECT 
    product_id, 
    product_name, 
    total_quantity / NULLIF(active_days, 0) AS avg_daily_quantity,
    RANK() OVER (ORDER BY total_quantity / NULLIF(active_days, 0) DESC) AS rank
FROM daily_sales;
